title: Engineered by Ananya
description: 'From Classroom to Industry: Bridging the DevSecOps Knowledge Gap with Open, Practical Learning.'
theme: just-the-docs

logo: "/assets/images/opendevsecops-transparent.png"
favicon_ico: "/assets/images/opendevsecops-favicon.ico"

url: https://ananyanandi31.github.io/engineered_by_ananya_n/
search_enabled: false

aux_links:
  Github: https://github.com/ananyanandi31
  Contribute: https://github.com/ananyanandi31/engineered_by_ananya_n

callouts:
  important:
    title: Important
    color: green
  warning:
    title: Warning
    color: yellow
  info:
    title: Info
    color: blue
  lab:
    title: Access The Lab
    color: purple
